package com.mvc.model;
// Generated Aug 31, 2017 10:21:47 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String shopname;
     private String username;
     private String password;
     private String email;
     private String name;
     private String surname;
     private String telephone;

    public User() {
    }

    public User(String shopname, String username, String password, String email, String name, String surname, String telephone) {
       this.shopname = shopname;
       this.username = username;
       this.password = password;
       this.email = email;
       this.name = name;
       this.surname = surname;
       this.telephone = telephone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getShopname() {
        return this.shopname;
    }
    
    public void setShopname(String shopname) {
        this.shopname = shopname;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

   
   



}


